networks:
  vaultwarden:
    external: false

services:
  vaultwarden:
    image: vaultwarden/server:1.35.3
    container_name: vaultwarden
    networks:
      - vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${VW_DOMAIN}
      SIGNUPS_ALLOWED: "true"
    volumes:
      - ./data/:/data/
        #- ./vw-data/:/data/
    ports:
      - 11001:80
