networks:
  mynetwork:
    external: true

services:
  dockhand:
    image: fnsys/dockhand:v1.0.18
    networks:
      - mynetwork
    container_name: dockhand
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data 
      - /srv/docker_lab/stacks:/srv/docker_lab/stacks
volumes:
  dockhand_data:

